# Generated by Django 4.2.1 on 2023-06-08 09:51

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('job', '0007_category_slug_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job.job')),
                ('cv', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='CV')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('job.job',),
        ),
        migrations.AddField(
            model_name='job',
            name='applicant',
            field=models.ManyToManyField(related_name='applicant_job', to='users.employer'),
        ),
    ]
