# Generated by Django 4.2.1 on 2023-06-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('job', '0007_category_slug_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_name', models.CharField(max_length=200)),
                ('date_applied', models.DateTimeField(auto_now=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_cv', to='users.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_jobs', to='job.cv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_jobs', to='job.job')),
            ],
        ),
    ]
