# Generated by Django 4.2.1 on 2023-06-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('job', '0008_job_applicant_alter_job_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Applicant1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='Applicant',
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('junior', 'junior'), ('intermediate', 'intermediate'), ('senior', 'senior'), ('expart', 'expart')], max_length=200),
        ),
        migrations.CreateModel(
            name='ApplicantCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_name', models.CharField(max_length=200)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_cv', to='users.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='applicant',
            field=models.ManyToManyField(to='users.applicant'),
        ),
        migrations.AddField(
            model_name='job',
            name='cv',
            field=models.ManyToManyField(to='job.job_applicant1'),
        ),
        migrations.AddField(
            model_name='job',
            name='each_cv',
            field=models.ManyToManyField(to='job.applicantcv'),
        ),
    ]
