# Generated by Django 4.2.1 on 2023-06-08 09:56

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_delete_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='job.job')),
                ('cv', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='CV')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('job.job',),
        ),
    ]
