# Generated by Django 4.2.1 on 2023-06-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_applicant1_remove_job_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='cv',
        ),
        migrations.DeleteModel(
            name='Job_Applicant1',
        ),
    ]
