# Generated by Django 4.2.1 on 2023-06-08 10:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('job', '0009_delete_job_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicant',
            field=models.ManyToManyField(related_name='applicant_job', to='users.applicant'),
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='CV')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_application', to='job.job')),
            ],
        ),
    ]
