# Generated by Django 4.2.1 on 2023-06-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_job_position'),
        ('job', '0010_alter_job_applicant_job_application'),
    ]

    operations = [
    ]
