# Generated by Django 4.2.1 on 2023-06-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_remove_job_cv_delete_job_applicant1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='each_cv',
            new_name='applicantCV',
        ),
        migrations.RemoveField(
            model_name='job',
            name='applicant',
        ),
    ]
