# Generated by Django 4.2.1 on 2023-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_remove_cv_cv_name_alter_cv_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
