# Generated by Django 4.2.1 on 2023-06-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('job', '0011_rename_each_cv_job_applicantcv_remove_job_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applicantCV',
        ),
        migrations.RenameModel(
            old_name='ApplicantCV',
            new_name='CV',
        ),
        migrations.CreateModel(
            name='Job_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.cv')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
