# Generated by Django 4.2.1 on 2023-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_delete_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='cv',
            field=models.ManyToManyField(related_name='applicant_CV', to='job.applicant_cv'),
        ),
    ]
