# Generated by Django 4.2.1 on 2023-06-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_cv_cv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
