# Generated by Django 4.2.1 on 2023-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_job_applicantcv_rename_applicantcv_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='date_applied',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
