# Generated by Django 4.2.1 on 2023-06-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_cv_cv_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cv_name',
        ),
    ]
