# Generated by Django 4.2.1 on 2023-06-11 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_cv_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_item',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_jobs', to='job.cv'),
        ),
        migrations.AlterField(
            model_name='job_item',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_jobs', to='job.job'),
        ),
    ]
